name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Build PdfRpt.Core lib
      run: dotnet build ./src/PdfRpt.Core/PdfRpt.Core.csproj --configuration Release